---
apiVersion: v1
kind: Secret
metadata:
  name: mailbridge-config
type: Opaque
stringData:
  MAILBRIDGE__API_TOKEN: # openssl rand -base64 32
  MAILBRIDGE__SMTP_ADDRESS:
  MAILBRIDGE__SMTP_FROM:
  MAILBRIDGE__SMTP_USERNAME:
  MAILBRIDGE__SMTP_PASSWORD:
  MAILBRIDGE__SMTP_TLS: # tls |  starttls | none

